[package]
name = "fluid_simulation"
version = "0.1.0"
authors = ["Thomas Byr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "*"
noise = "*"
rand = "*"
fps_counter = "*"
find_folder = "*"
